### PR TITLE
ok so basically

### PR DESCRIPTION
**Pull request by deletescape**
it is really speed now

### CODE REVIEW

**Comment by whoknowswhoiam** [comment]
Tillie I love you but keks are from @raphielscape only 😘

**Comment by whoknowswhoiam** [comment]
@whoknowswhoiam lol

**Comment by anirudhgupta109** [comment]
#TillBestKernelDev2k18

**Comment by raphielscape** [comment]
Me approve this commit

**Comment by raphielscape** [comment]
This pull request shall reopened

**Comment by 4PERTURE** [comment]
I approve this

**Comment by akhilnarang** [comment]
*_*

**Comment by akhilnarang** [comment]
Uh
`*_*`

**Comment by mracar07** [comment]
Wow. Naice

**Comment by songotenks69** [comment]
?-?

**Comment by 4PERTURE** [comment]
O_O

**Comment by songotenks69** [comment]
Such references

**Comment by whoknowswhoiam** [comment]
> Such references

smh don't bring back dead memes

**Pull request closed without merging**
